package com.undyingideas.thor.skafottet.firebase.controller;

import com.firebase.client.Firebase;
import com.undyingideas.thor.skafottet.PlayerScore;
import com.undyingideas.thor.skafottet.firebase.DTO.LobbyDTO;
import com.undyingideas.thor.skafottet.firebase.DTO.LobbyPlayerStatus;
import com.undyingideas.thor.skafottet.firebase.DTO.PlayerDTO;
import com.undyingideas.thor.skafottet.firebase.DTO.WordStatus;
import com.undyingideas.thor.skafottet.wordlist.data.WordList;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 * Created by theis on 05-01-2016.
 */
public class LobbyController {

    Firebase lobbyRef;
    LobbyDTO lobbyDTO;

    public LobbyController(final Firebase ref, LobbyDTO lobbyDTO){

        lobbyRef = ref.child("Lobby");
        this.lobbyDTO = lobbyDTO;

    }

    public void createLobby(LobbyDTO lobbyDTO){

        //This genetates uniqe ID in firebase
        final Firebase newPostRef = lobbyRef.push();

        //Putting the player object into a hashmap with "player" key.

        // TODO : Replace with SparseArray if possible
        final Map<String, LobbyDTO> post1 = new HashMap<>();
        post1.put("Lobby", lobbyDTO);
        newPostRef.setValue(post1);

        // Get the unique ID generated by push()
        final String postId = newPostRef.getKey();

    }
}
